-- ---------------------------------------------------------------------------
-- Phase 6.6.1 — Bug Hunter (BugBountyEscrow integration).
--
-- Two tables:
--   bug_reports       one row per submitted report, full lifecycle state.
--   bug_claim_tokens  one-time claim tokens issued after admin approval.
--
-- Design notes:
-- - reward_amount, severity classification, approval, tx_hash are NEVER
--   writable by the reporting user (Section 3/18) — RLS below only grants
--   INSERT of a narrow initial column set and SELECT of own rows. Every
--   status/reward/approval mutation happens through service-role routes
--   (app/api/admin/bug-hunter/*, app/api/bug-hunter/claim/*), same pattern
--   as reward_submissions in 2026-08-earn-rewards.sql.
-- - claim tokens are stored HASHED (sha256), never plaintext — same reason
--   password hashes aren't stored plaintext. The route that emails the
--   claim link is the only place that ever sees the raw token.
-- - state machine is enforced with a CHECK constraint AND the application
--   layer only ever does conditional UPDATE ... WHERE status = 'X' (see
--   lib/bugHunter/store.ts), so a race between two admin clicks or two
--   claim submissions can't double-transition a row.
-- ---------------------------------------------------------------------------

create table if not exists bug_reports (
  id uuid primary key default gen_random_uuid(),
  public_id text not null unique, -- "BUG-000001" style, generated by app (sequence below)

  user_id uuid references auth.users(id) on delete set null,
  wallet_address text not null, -- lowercased BSC testnet address supplied by the researcher
  email text not null,

  title text not null,
  category text not null,
  severity text not null check (severity in ('low', 'medium', 'high', 'critical')),
  description text not null,
  reproduction_steps text not null,
  expected_behavior text not null,
  actual_behavior text not null,
  impact text not null,
  evidence_path text not null, -- Supabase Storage object path, bucket "bug-hunter-evidence"

  status text not null default 'PENDING'
    check (status in ('PENDING', 'APPROVED', 'REJECTED', 'CLAIMING', 'REWARDED')),

  reward_amount numeric(38, 18), -- ELS, set only by admin on approval
  bounty_id text, -- bytes32 hex used on BugBountyEscrow, set when the bounty is prepared on-chain
  tx_hash text, -- claimBounty transaction hash, set only after on-chain confirmation

  approved_by text,
  approved_at timestamptz,
  rejected_reason text,
  claimed_at timestamptz,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists bug_reports_user_id_idx on bug_reports(user_id);
create index if not exists bug_reports_status_idx on bug_reports(status);
create index if not exists bug_reports_wallet_idx on bug_reports(wallet_address);

-- Sequence-backed public ID generator: BUG-000001, BUG-000002, ...
create sequence if not exists bug_reports_public_id_seq;

create or replace function bug_reports_generate_public_id()
returns trigger as $$
begin
  if new.public_id is null or new.public_id = '' then
    new.public_id := 'BUG-' || lpad(nextval('bug_reports_public_id_seq')::text, 6, '0');
  end if;
  return new;
end;
$$ language plpgsql;

drop trigger if exists trg_bug_reports_public_id on bug_reports;
create trigger trg_bug_reports_public_id
  before insert on bug_reports
  for each row execute function bug_reports_generate_public_id();

create or replace function bug_reports_set_updated_at()
returns trigger as $$
begin
  new.updated_at := now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists trg_bug_reports_updated_at on bug_reports;
create trigger trg_bug_reports_updated_at
  before update on bug_reports
  for each row execute function bug_reports_set_updated_at();

alter table bug_reports enable row level security;

-- Users may read only their own reports. All writes happen server-side via
-- the service-role client (RLS bypassed there by design, same as every
-- other admin-mutated table in this project) — no INSERT/UPDATE policy is
-- granted to the anon/authenticated role at all, so a compromised anon key
-- alone cannot create or alter rows.
drop policy if exists bug_reports_select_own on bug_reports;
create policy bug_reports_select_own on bug_reports
  for select
  using (auth.uid() = user_id);

-- ---------------------------------------------------------------------------

create table if not exists bug_claim_tokens (
  id uuid primary key default gen_random_uuid(),
  bug_report_id uuid not null references bug_reports(id) on delete cascade,
  token_hash text not null unique, -- sha256(raw token), hex
  expires_at timestamptz not null,
  used_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists bug_claim_tokens_report_idx on bug_claim_tokens(bug_report_id);
create index if not exists bug_claim_tokens_hash_idx on bug_claim_tokens(token_hash);

alter table bug_claim_tokens enable row level security;

-- No policies granted at all — this table is never read/written from the
-- browser under any circumstance, only from service-role server routes.
-- RLS enabled with zero policies means "deny all" for anon/authenticated.

-- ----------------------------------------------------------------------------
-- Storage bucket for bug report evidence (screenshots)
-- ----------------------------------------------------------------------------
-- Run once, separately, from the Supabase dashboard (Storage -> New bucket)
-- or via the CLI — bucket creation isn't a plain SQL statement:
--   1. Create a bucket named "bug-hunter-evidence", set to PRIVATE (not
--      public — unlike "trade-screenshots" in supabase/schema.sql, evidence
--      may contain sensitive info the reporting user didn't intend to be
--      publicly guessable-URL-accessible).
--   2. No public INSERT/SELECT policy needed: uploads go through
--      /api/bug-hunter/report (service-role key), and admin viewing goes
--      through /[adminEntry]/api/bug-hunter/[id]/evidence-url, which mints
--      a short-lived (5 min) signed URL server-side after an admin session
--      check. Object paths are random UUIDs, never derived from user input.
