-- ---------------------------------------------------------------------------
-- Phase 6.6.4 — Suggestions (Earn contribution path #2, alongside Bug Hunter).
--
-- Deliberately reuses the EXISTING generic reward distributor
-- (contracts/ELSTestnetRewardDistributor.sol via lib/rewards/distributor.ts
-- distribute(user, amount, claimId)) instead of the Bug Hunter escrow
-- contract — there is no per-submission on-chain "prepare" step needed
-- (no researcher-initiated claimBounty tx), so a suggestion's ELS reward is
-- paid out server-side once approved, exactly like Eligible Reward Center
-- (supabase/migrations/2026-08-eligible-reward.sql) does. claim_id is this
-- table's OWN id-space (keccak256 of "suggestion:<row id>"), never reused
-- from bug_reports or eligible_reward_claims, so the on-chain replay guard
-- can't collide across systems.
--
-- Status model (brief's SUBMITTED -> UNDER REVIEW -> APPROVED/REJECTED ->
-- REWARD AVAILABLE -> CLAIM -> ELS DISTRIBUTION), collapsed to what the DB
-- actually needs to enforce:
--   PENDING   — submitted, awaiting admin review ("under review" is just
--               the UI label for a PENDING row with no reward_amount yet).
--   APPROVED  — admin set a reward_amount; this IS "REWARD AVAILABLE" —
--               claimable, not yet claimed.
--   REJECTED  — terminal, no reward.
--   CLAIMING  — user's claim is in flight (guards double-claim races).
--   CLAIMED   — terminal, reward paid.
--
-- A submission alone never grants ELS (Security/Anti-abuse requirement):
-- reward_amount starts NULL and is set ONLY by the admin approve route,
-- server-side, never from client input on submit.
-- ---------------------------------------------------------------------------

create table if not exists suggestions (
  id uuid primary key default gen_random_uuid(),
  public_id text not null unique, -- "SUG-000001" style, generated by app (sequence below)

  user_id uuid references auth.users(id) on delete set null,
  wallet_address text not null, -- lowercased, same convention as bug_reports/reward_submissions
  email text,

  title text not null,
  category text not null,
  description text not null,
  supporting_info text,

  status text not null default 'PENDING'
    check (status in ('PENDING', 'APPROVED', 'REJECTED', 'CLAIMING', 'CLAIMED')),

  -- ELS reward. NEVER writable by the submitting user — set only by the
  -- admin approve route, same rule as bug_reports.reward_amount.
  -- totalElsReward = base_reward_els + admin_bonus_els, computed and
  -- persisted server-side at approval time (see approveSuggestion in
  -- lib/suggestions/store.ts). reward_amount stores that computed total —
  -- it is what the claim flow (lib/suggestions/claim.ts) actually pays out
  -- — while base_reward_els/admin_bonus_els are kept as their own columns
  -- purely for audit/display (Admin Control Center shows the breakdown).
  base_reward_els numeric(38, 18) not null default 0,
  admin_bonus_els numeric(38, 18) not null default 0,
  reward_amount numeric(38, 18),
  claim_id text unique, -- bytes32 hex passed to distribute()'s claimId, assigned on approval
  tx_hash text, -- distribute() transaction hash, set only after on-chain confirmation

  -- AI Energy grant. Fixed at SUGGESTION_AI_ENERGY_REWARD (10) — never an
  -- admin- or client-supplied number. Separate ledger (lib/energy.ts /
  -- ai_token), NOT routed through the ELS distributor. Granted immediately
  -- on approval (never on submission), and only once per suggestion —
  -- ai_energy_granted_at being non-null is the guard against a double-grant
  -- on a retried approve call.
  ai_energy_amount numeric not null default 0,
  ai_energy_granted_at timestamptz,

  approved_by text,
  approved_at timestamptz,
  rejected_reason text,
  claimed_at timestamptz,
  last_error_message text,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists suggestions_user_id_idx on suggestions(user_id);
create index if not exists suggestions_status_idx on suggestions(status);
create index if not exists suggestions_wallet_idx on suggestions(wallet_address);

-- Sequence-backed public ID generator: SUG-000001, SUG-000002, ...
create sequence if not exists suggestions_public_id_seq;

create or replace function suggestions_generate_public_id()
returns trigger as $$
begin
  if new.public_id is null or new.public_id = '' then
    new.public_id := 'SUG-' || lpad(nextval('suggestions_public_id_seq')::text, 6, '0');
  end if;
  return new;
end;
$$ language plpgsql;

drop trigger if exists trg_suggestions_public_id on suggestions;
create trigger trg_suggestions_public_id
  before insert on suggestions
  for each row execute function suggestions_generate_public_id();

create or replace function suggestions_set_updated_at()
returns trigger as $$
begin
  new.updated_at := now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists trg_suggestions_updated_at on suggestions;
create trigger trg_suggestions_updated_at
  before update on suggestions
  for each row execute function suggestions_set_updated_at();

alter table suggestions enable row level security;

-- Same rule as bug_reports: users may read only their own rows. All writes
-- happen server-side via the service-role client — no INSERT/UPDATE policy
-- is granted to anon/authenticated at all.
drop policy if exists suggestions_select_own on suggestions;
create policy suggestions_select_own on suggestions
  for select
  using (auth.uid() = user_id);
